server:
  servlet:
    context-path: /v1/reddit-clone

springbootdvega:
#  welcome-message: "Hey Amanda, this message overrode the default and was specified in application.yml"

spring:
  profiles:
    active: dev
  h2:
    console:g
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  # access h2 web console and ensure the JDBC URL matches. User is sa with no password (by default).
  datasource:
    url: jdbc:h2:mem:testdb

info:
  application:
    name: spring-boot-dvega
    description: Reddit clone built with SpringBoot
    version: 0.0.1

  endpoint:
    health:
      show-details: always

management:
  endpoints:
    web:
      exposure:
        include:
          - info
          - health