server:
  servlet:
    context-path: /v1/reddit-clone

springbootdvega:
  welcome-message: "Hey Amanda, this message overrode the default and was specified in application.yml"

spring:
  profiles:
    active: dev
info:
  application:
    name: spring-boot-dvega
    description: Reddit clone built with SpringBoot
    version: 0.0.1

  endpoint:
    health:
      show-details: always

management:
  endpoints:
    web:
      exposure:
        include:
          - info
          - health